services:
  postgres:
    container_name: postgres-sql-rtc
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: realtime_chat
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - realtime-chat
    restart: unless-stopped
  keycloak:
    container_name: keycloak-rtc
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - realtime-chat
    command:
      - "start-dev"

networks:
  realtime-chat:
    driver: bridge

volumes:
  postgres:
    driver: local